[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "14.15.3", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "14.15.3", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"
  NODE_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy-Report-Only = "default-src 'self' https://rsms.me https://api.netlify.com https://fonts.gstatic.com; frame-ancestors 'none'; style-src 'self' https://rsms.me https://fonts.googleapis.com 'unsafe-inline'; script-src 'self' https://www.googletagmanager.com 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob:; img-src 'self' www.googletagmanager.com https://d33wubrfki0l68.cloudfront.net data:; connect-src 'self' https://www.google-analytics.com https://rsms.me; report-uri https://khoivan.report-uri.com/r/d/csp/wizard;"
#    Content-Security-Policy = "default-src 'self' https://rsms.me https://api.netlify.com; style-src 'self' https://rsms.me 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob:;"
    # X-Content-Type-Options = "nosniff"
    # X-Frame-Options = "DENY"
    # X-XSS-Protection = "1; mode=block"