module.exports = [
  { name: 'hexane', eluoValue: 0.01 },
  { name: 'heptane', eluoValue: 0.01 },
  { name: '2,2,4-trimethylpentane', eluoValue: 0.01 },
  { name: '1,1,2-trichloro-1,2,2-trifluoroethane', eluoValue: 0.02 },
  { name: 'cyclohexane', eluoValue: 0.03 },
  { name: 'toluene', eluoValue: 0.22 },
  { name: 'chloroform (hydrocarbon stabilized)', eluoValue: 0.26 },
  { name: 'diethyl ether', eluoValue: 0.29 },
  { name: 'methyl t-butyl ether', eluoValue: 0.29 },
  { name: 'chloroform', eluoValue: 0.31 },
  { name: 'dichloromethane', eluoValue: 0.32 },
  { name: 'tetrahydrofuran', eluoValue: 0.35 },
  { name: 'methyl ethyl ketone', eluoValue: 0.39 },
  { name: 'acetone', eluoValue: 0.43 },
  { name: 'ethyl acetate', eluoValue: 0.45 },
  { name: 'acetonitrile', eluoValue: 0.5 },
  { name: 'isobutanol', eluoValue: 0.54 },
  { name: 'pyridine', eluoValue: 0.55 },
  { name: '2-propanol', eluoValue: 0.63 },
  { name: 'ethanol', eluoValue: 0.65 },
  { name: 'methanol', eluoValue: 0.73 },
  { name: 'water', eluoValue: 1.0 },
];
